@host = http://localhost:3501/api/v1


GET {{host}}/userDetails/check-email?email=dor@xample.com
###
POST {{host}}/userDetails/login
content-Type: application/json

{
  "email": "dor@example.com" , 
  "password": "securePassword123"
}
###
PUT {{host}}/userDetails/location/30
content-Type: application/json

{
  "city": "Netantya" , 
  "latitude": 40.6666,
  "longitude": 40.7777
}
###

DELETE {{host}}/userDetails/delete/31
content-Type: application/json

###

POST {{host}}/userPreferences/register
content-Type: application/json

{
  "userId": 31,
  "preferredPartner": "female",
  "relationshipType": "long-term",
  "heightPreferences": "170",
  "religion": "none",
  "isSmoker": false,
  "preferredDistanceKm": 50,
  "minAgePreference": 25,
  "maxAgePreference": 35,
  "interests": "music,travel,sports"
}
###
PUT http://10.0.0.20:3501/api/v1/userDetails/register
Content-Type: application/json

{
  "preferredPartner": "male",
  "preferredDistanceKm": 100,
  "minAgePreference": 18,
  "maxAgePreference": 24
}
###
PUT {{host}}/userPreferences/updateUser/21
Content-Type: application/json

{
  "relationshipType": "male",
  "heightPreferences": "152",
  "religion": "Hindu",
  "isSmoker": false,
  "interests": "Traveling,Gaming,Shy,Adventurous,Music"
}
###
POST {{host}}/matches/add
content-Type: application/json

{
  "User1ID": 30 , 
  "User2ID": 32,
  "MatchStatus": "true"
}
###

GET {{host}}/matches/matched-users/32
###