/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/DataContextProvider`; params?: Router.UnknownInputParams; } | { pathname: `/firebase`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/login`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/chats` | `/chats`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/main` | `/main`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/profile` | `/profile`; params?: Router.UnknownInputParams; } | { pathname: `/registerPages/addImage`; params?: Router.UnknownInputParams; } | { pathname: `/registerPages/datingPreference`; params?: Router.UnknownInputParams; } | { pathname: `/registerPages/emailAndPassword`; params?: Router.UnknownInputParams; } | { pathname: `/registerPages/location`; params?: Router.UnknownInputParams; } | { pathname: `/registerPages/personalDetails`; params?: Router.UnknownInputParams; } | { pathname: `/registerPages/verificationNumber`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/DataContextProvider`; params?: Router.UnknownOutputParams; } | { pathname: `/firebase`; params?: Router.UnknownOutputParams; } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/login`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/chats` | `/chats`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/main` | `/main`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/profile` | `/profile`; params?: Router.UnknownOutputParams; } | { pathname: `/registerPages/addImage`; params?: Router.UnknownOutputParams; } | { pathname: `/registerPages/datingPreference`; params?: Router.UnknownOutputParams; } | { pathname: `/registerPages/emailAndPassword`; params?: Router.UnknownOutputParams; } | { pathname: `/registerPages/location`; params?: Router.UnknownOutputParams; } | { pathname: `/registerPages/personalDetails`; params?: Router.UnknownOutputParams; } | { pathname: `/registerPages/verificationNumber`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/DataContextProvider${`?${string}` | `#${string}` | ''}` | `/firebase${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `/login${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/chats${`?${string}` | `#${string}` | ''}` | `/chats${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/main${`?${string}` | `#${string}` | ''}` | `/main${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/profile${`?${string}` | `#${string}` | ''}` | `/profile${`?${string}` | `#${string}` | ''}` | `/registerPages/addImage${`?${string}` | `#${string}` | ''}` | `/registerPages/datingPreference${`?${string}` | `#${string}` | ''}` | `/registerPages/emailAndPassword${`?${string}` | `#${string}` | ''}` | `/registerPages/location${`?${string}` | `#${string}` | ''}` | `/registerPages/personalDetails${`?${string}` | `#${string}` | ''}` | `/registerPages/verificationNumber${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/DataContextProvider`; params?: Router.UnknownInputParams; } | { pathname: `/firebase`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/login`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/chats` | `/chats`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/main` | `/main`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/profile` | `/profile`; params?: Router.UnknownInputParams; } | { pathname: `/registerPages/addImage`; params?: Router.UnknownInputParams; } | { pathname: `/registerPages/datingPreference`; params?: Router.UnknownInputParams; } | { pathname: `/registerPages/emailAndPassword`; params?: Router.UnknownInputParams; } | { pathname: `/registerPages/location`; params?: Router.UnknownInputParams; } | { pathname: `/registerPages/personalDetails`; params?: Router.UnknownInputParams; } | { pathname: `/registerPages/verificationNumber`; params?: Router.UnknownInputParams; };
    }
  }
}
