/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/DataContextProvider`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/registerPages/datingPreference`; params?: Router.UnknownInputParams; } | { pathname: `/registerPages/emailAndPassword`; params?: Router.UnknownInputParams; } | { pathname: `/registerPages/location`; params?: Router.UnknownInputParams; } | { pathname: `/registerPages/personalDetails`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/DataContextProvider`; params?: Router.UnknownOutputParams; } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `/registerPages/datingPreference`; params?: Router.UnknownOutputParams; } | { pathname: `/registerPages/emailAndPassword`; params?: Router.UnknownOutputParams; } | { pathname: `/registerPages/location`; params?: Router.UnknownOutputParams; } | { pathname: `/registerPages/personalDetails`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/DataContextProvider${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `/registerPages/datingPreference${`?${string}` | `#${string}` | ''}` | `/registerPages/emailAndPassword${`?${string}` | `#${string}` | ''}` | `/registerPages/location${`?${string}` | `#${string}` | ''}` | `/registerPages/personalDetails${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/DataContextProvider`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/registerPages/datingPreference`; params?: Router.UnknownInputParams; } | { pathname: `/registerPages/emailAndPassword`; params?: Router.UnknownInputParams; } | { pathname: `/registerPages/location`; params?: Router.UnknownInputParams; } | { pathname: `/registerPages/personalDetails`; params?: Router.UnknownInputParams; };
    }
  }
}
